### ISSUE TITLE
[feauture] Query 缺少实例方法 getByObjectId

### ISSUE THREAD

**Issue by wujun4code** [leancloud/swift-sdk#1]
对应的 objc 的方法如下：

```objc
    AVQuery *query = [AVQuery queryWithClassName:@"Todo"];
    [query getObjectInBackgroundWithId:@"558e20cbe4b060308e3eb36c" block:^(AVObject *object, NSError *error) {
        // object 就是 id 为 558e20cbe4b060308e3eb36c 的 Todo 对象实例
    }];
```

**Comment by tang3w** [comment]
从 API 设计的角度来说，get 方法可能作为静态方法比较合适，因为这个方法和查询条件是相互独立的。

**Comment by tang3w** [comment]
经过讨论，get 方法应该作为实例方法。所有 SDK 都应该在 Query 的 get 和 getFirst 方法中带上查询条件，且不应该有副作用（不能修改现有的查询条件）。已经在 https://github.com/leancloud/swift-sdk/commit/e2f31c0115d9fa3c3352f5d6ac8de6077d83dc39 中实现。
