### ISSUE TITLE
Installation 强制填写 teamID

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/swift-sdk#107]
https://leanticket.cn/tickets/18842

有的用户使用不同的 Apple 开发者账号进行分发和测试。如果 Installation 表的数据没有 teamID，那么后端无法判断哪个是测试环境，哪个是生产环境。所以应该强制用户其填写 teamID。

**Comment by zapcannon87** [comment]
topicID 也强制填写或者 SDK 自动添加 bundleIdentifier 吧。

**Comment by zapcannon87** [comment]
还是改 API 吧，隐藏 deviceToken 和 teamId，增加一个强制设置这两个值的 set function。这样就能在编译层发现改动了。

另外 deviceToken 获取时都是 Data Type 吧，SDK 可以考虑把转换逻辑加上。

**Comment by tang3w** [comment]
Good idea。我觉得把要强制设置的字段变成 public private(set) 可能比隐藏起来好。
