### ISSUE TITLE
把 HTTP 错误的 body 暴露给用户

### ISSUE THREAD

**Issue by tang3w** [leancloud/swift-sdk#109]
目前 LCError 没有包含 HTTP body，导致用户无法查看错误原因。

**Comment by tang3w** [comment]
我的初步想法是把所有 Result 类型关联的 Error 都改成 LCError，并把 HTTP body 关联到 LCError 中。

@zapcannon87 你有什么建议吗？

**Comment by zapcannon87** [comment]
* 假设用户发起一个请求，然后得到了「非 2xx 的 HTTP  body」
    * 如果我是 App 开发者，好像除了告知 App 使用者服务器异常（弹出提示），也没其它能做的了
    * 有用户提出过要使用「非 2xx 的 HTTP body」 的需求吗？

* 假设用户想要使用「非 2xx 的 HTTP body」，那么在现有的基础上
    * LCError 的 code 和 reason 肯定是不能使用的，因为 HTTP status code 和我们的服务端错误有交集，有些用户可能不是很严谨，只检查 code == XXX，不管 error domain，所以 LCError 的 code 和 reason 只能用在我们定义的服务器错误以及 SDK 定义的内部错误上
    * 可以使用 userInfo，把 HTTP response header 和 body 都放进去，用于取值的 key 暴露给用户，附带文档说明

**Comment by tang3w** [comment]
> 有用户提出过要使用「非 2xx 的 HTTP body」 的需求吗？

有这样的需求。例如当注册用户时，如果用户名已经被占用，app 可检查表示「用户名已被占用」的错误码来提示用户更换一个用户名。所以我觉得 LCError 应该优先表示 HTTP body 中给出的错误，如果响应未给出错误的 HTTP body，才表示 HTTP 请求错误。

目前 HTTP body 中的错误只有 code 和 reason 两个字段，刚好可以把它们拿出来放在 LCError 中。

**Comment by zapcannon87** [comment]
等等，可能我的理解有误，你说的 http body 里的错误，就是我们[服务端定义的错误](https://leancloud.cn/docs/error_code.html)吧？

**Comment by tang3w** [comment]
是的。现在 Result 关联的 Error 没有把「服务端定义的错误」表示出来，因此计划改成 LCError 并且把它们表示出来。

**Comment by zapcannon87** [comment]
我前面理解为 HTTP Status code 了，比如 404 这样。。。不过这不重要。

如果是我们「服务端定义的错误」，那肯定是直接给用户用啊，我看了代码，[这里](https://github.com/leancloud/swift-sdk/blob/62f73e898a687803991f715dbc2c6a7ad52133e7/Sources/Foundation/Error.swift#L43)以及[这里](https://github.com/leancloud/swift-sdk/blob/62f73e898a687803991f715dbc2c6a7ad52133e7/Sources/Storage/ObjectProfiler.swift#L624)是相关代码，但是没有被使用，是不是某个版本改的时候漏了？

最后就是 LCError 的 code 和 reason 只用在我们的「服务端定义的错误」和「SDK 定义的内部错误」上，不要用在其它地方了，避免冲突。

**Comment by tang3w** [comment]
不是改漏了，是一直没有全面支持。

我看服务端定义的与 HTTP 状态码冲突的错误码跟 HTTP 状态码的语义是一致的，例如 4xx 状态码。既然没有冲突，是不是就没有用 underlyingError 的必要了？如果用 underlyingError，虽然确实把 HTTP 状态码和其他错误分开了，但用户需要关注两层错误。

**Comment by tang3w** [comment]
要不就彻底一点，把内部错误和服务端定义的错误也分开吧，虽然它们的 code 暂时没有冲突。

我在想是否能重新设计错误类型，以把它们严格区分开来。例如用枚举来表示和区分这三种错误：

```swift
enum ErrorCategory {
    case http(error: Error)
    case api(error: Error, httpError: Error)
    case sdk(error: Error)
}
```

**Comment by zapcannon87** [comment]
这个也要暴露给开发者吗？

**Comment by tang3w** [comment]
是的。或者给 LCError 增加一个属性，表示它的类型。只有引入一个这样的纬度，才能把各个错误彻底区分开。否则各种错误类型还是会纠缠在一起。

**Comment by tang3w** [comment]
但是感觉这样又太复杂了。

**Comment by tang3w** [comment]
嗯，那还是按照之前的讨论来做。

**Comment by tang3w** [comment]
Solved in 15.0.0
