### ISSUE TITLE
cocopods找不到最新版本

### ISSUE THREAD

**Issue by mintoRo** [leancloud/swift-sdk#116]
你好 按照最新文档集成后，pod总是安装不了，总是提示：

> [!] CocoaPods could not find compatible versions for pod "LeanCloud":
>   In Podfile:
>     LeanCloud (~> 13.0.0)
> 
> Specs satisfying the `LeanCloud (~> 13.0.0)` dependency were found, but they required a higher minimum deployment target.

当我在PodFile不指定版本时 （pod 'LeanCloud'）
可以install 但是发现安装是 11.0.1的 版本

然后，通过pod search LeanCloud 发现 是可以搜到15.0.0最新版的

**Comment by zapcannon87** [comment]
> 你好 按照最新文档集成后，pod总是安装不了，总是提示：
> 
> > [!] CocoaPods could not find compatible versions for pod "LeanCloud":
> > In Podfile:
> > LeanCloud (~> 13.0.0)
> > Specs satisfying the `LeanCloud (~> 13.0.0)` dependency were found, but they required a higher minimum deployment target.
> 
> 当我在PodFile不指定版本时 （pod 'LeanCloud'）
> 可以install 但是发现安装是 11.0.1的 版本
> 
> 然后，通过pod search LeanCloud 发现 是可以搜到15.0.0最新版的

13.0.0 以后，支持的 iOS 最小版本是 10.0.0，详情见 [这里](https://github.com/leancloud/swift-sdk/blob/13.0.0/LeanCloud.podspec)

**Comment by mintoRo** [comment]
解决了 感谢
