### ISSUE TITLE
An issue of SMS

### ISSUE THREAD

**Issue by dowhilenet** [leancloud/swift-sdk#13]
```
        LCSMS.requestShortMessage(mobilePhoneNumber: phoneNumber, templateName: "", variables: nil) { (res) in
            if res.isSuccess {
                print("success")
            }
            if res.isFailure {
                print("failure")
            }
        }
```
`templateName` represents what?

**Comment by tang3w** [comment]
Before requesting a short message, you should create a short message template on LeanCloud application console. Each short message template has a name, which is the meaning of `templateName` here.
