### ISSUE TITLE
LCRelation 提供一个 query 接口返回一个 LeanCloud.Query 对象

### ISSUE THREAD

**Issue by wujun4code** [leancloud/swift-sdk#2]
类似 oc 的 接口https://leancloud.cn/api-docs/iOS/Classes/AVRelation.html#//api/name/query

**Comment by tang3w** [comment]
已在 https://github.com/leancloud/swift-sdk/commit/9426089d096d9b2b38b1664d48d9c3dee20346e1 中实现。
