### ISSUE TITLE
希望尽快适配swift3，Alamofire升级到4.0

### ISSUE THREAD

**Issue by jsjjkfc** [leancloud/swift-sdk#20]

**Comment by lou-lan** [comment]
希望尽快适配swift3

**Comment by tang3w** [comment]
计划在本周内完成对 Swift 3.0 的支持。

**Comment by lou-lan** [comment]
可以了吗

**Comment by jsjjkfc** [comment]
难点在哪里？等着急用呢。。

**Comment by tang3w** [comment]
尽量在周一前做，上周被一些事情耽搁了。有一个名为 swift3 的分支兼容 Swift 3.0 Preview，尚未测试与正式版的兼容性。

**Comment by jsjjkfc** [comment]
那个分支我用过了，主要Alamofire没有升级到最新，全是Alamofire报的错==

**Comment by tang3w** [comment]
谢谢你提供信息，我尽快兼容。

**Comment by tang3w** [comment]
兼容需要做的工作比想象中的要多一些，不过正在有序地进行。

**Comment by jsjjkfc** [comment]
辛苦了～

**Comment by tang3w** [comment]
Swift 3 已经兼容完毕，更新到分支 [swift3](https://github.com/leancloud/swift-sdk/tree/swift3) 中了。 @jsjjkfc @lou-lan

**Comment by jsjjkfc** [comment]
太感谢！
