### ISSUE TITLE
Restart APP logon status lost

### ISSUE THREAD

**Issue by wooseng** [leancloud/swift-sdk#241]
i logon success, but when i restart app, logon status lost, i must re login

**Comment by zapcannon87** [comment]
auto caching data of current user has not been supported.

we will add this feature in the future, you can track it in this issue: https://github.com/leancloud/swift-sdk/issues/221

**Comment by wooseng** [comment]
thanks, i just found this feature at the document, but it doesn't work in my app.

**Comment by zapcannon87** [comment]
> it doesn't work in my app

what doesn't work in your app?

**Comment by wooseng** [comment]
auto caching data of current user, i think you can change the document or add this feature.
<img width="1000" alt="WX20190929-203846@2x" src="https://user-images.githubusercontent.com/22250024/65832655-37a7f900-e2f9-11e9-9376-8fadb16c131e.png">

**Comment by zapcannon87** [comment]
thanks for feedback, it's a bug of the docs, we will fix it.
