### ISSUE TITLE
能否加入Carthage的支持？

### ISSUE THREAD

**Issue by pangpingfei** [leancloud/swift-sdk#30]
或者release源码中提供Framework下载，因为不使用pod。谢谢！

**Comment by ncw1992120** [comment]
试过github "https://github.com/leancloud/swift-sdk"会产生编译错误，期待能尽快支持

**Comment by tang3w** [comment]
测试是可以编译的，Cartfile 如下：

github "leancloud/swift-sdk" ~> 12.0.0

先关闭了，如果有问题再反馈。
