### ISSUE TITLE
WKWebView 冲突

### ISSUE THREAD

**Issue by HawkinsZhao** [leancloud/swift-sdk#39]
LeanCloud 开发团队，您好！

我在使用 Swift SDK 的时候遇到了一个严重的问题，就是如果引入 WebKit，并在代码中创建一个 WKWebView 的对象之后就会报错。这个错误非常容易复现，根据错误信息来看是 WKWebView  与 SDK 本身有冲突。

希望能得到您的回复
十分感谢！

![screen shot 2017-03-28 at 11 16 07 pm](https://cloud.githubusercontent.com/assets/11468820/24413089/fa0a05ce-140c-11e7-814a-d89c1009a917.png)

**Comment by tang3w** [comment]
应该在 #41 中修复了，请确认一下，谢谢你的反馈。

**Comment by tang3w** [comment]
已在 10.0.1 中修复。
