### ISSUE TITLE
The result of response should be .failure when Forbidden writing by object's ACL

### ISSUE THREAD

**Issue by hustlzp** [leancloud/swift-sdk#395]
The codes:

```swift
self.delete(completionQueue: .main) { (result) in
    switch result {
    case .success:
        seal.fulfill(())
    case .failure(error: let error):
        seal.reject(error)
    }
}
```

The response:
![image](https://user-images.githubusercontent.com/1180240/97099253-1400df00-16c2-11eb-84b8-2d145cf3e378.png)

and result in success (should be failure):

![image](https://user-images.githubusercontent.com/1180240/97099262-21b66480-16c2-11eb-85b1-dae3d075f2c6.png)

**Comment by zapcannon87** [comment]
感谢反馈，已确认是 bug，会在下个版本修复。
