### ISSUE TITLE
Some crash bugs, Please check them out

### ISSUE THREAD

**Issue by IsanHu** [leancloud/swift-sdk#396]
The version is 17.6.1
![image](https://user-images.githubusercontent.com/3689943/97957942-2926ed80-1de7-11eb-830e-af84fdb19f88.png)
This one has produced 1056 crashes...

![image](https://user-images.githubusercontent.com/3689943/97958026-5d9aa980-1de7-11eb-8a67-34ba758538ed.png)

![image](https://user-images.githubusercontent.com/3689943/97958163-a3f00880-1de7-11eb-81d4-3c43f6284e3c.png)

**Comment by zapcannon87** [comment]
In general the crash due to multi-thread access, and `LCObject` is **NOT** thread-safety, please ensure your code is thread-safe.

or you can wait this feature: https://github.com/leancloud/swift-sdk/issues/244

**Comment by IsanHu** [comment]
> In general the crash due to multi-thread access, and `LCObject` is **NOT** thread-safety, please ensure your code is thread-safe.
> 
> or you can wait this feature: #244

![image](https://user-images.githubusercontent.com/3689943/97973422-00135680-1e01-11eb-864e-5fe7020c90fe.png)
The Inner code executes on which thread seems like your sdk's duty...

**Comment by zapcannon87** [comment]
Possible case: the thread you created and the thread in SDK access object concurrently.
