### ISSUE TITLE
iOS 10.3 init sdk时崩溃

### ISSUE THREAD

**Issue by ZuYuanZhou** [leancloud/swift-sdk#40]
LeanCloud.initialize(applicationID: "xxx", applicationKey: "xxxxx")

![image](https://cloud.githubusercontent.com/assets/749939/24487103/0c9bf6f0-1540-11e7-9508-958ff024338e.png)

**Comment by tang3w** [comment]
我们在 10.3.1 上测试没有复现这个问题，请问在 10.3 中会固定复现吗？

**Comment by chn-lyzhi** [comment]
同样问题，Xcode 为 8.3，iOS 为 10.3.1.

**Comment by tang3w** [comment]
@chn-lyzhi 请问这个问题是每次都会复现的吗？

**Comment by tang3w** [comment]
我们这边始终无法复现这个问题，能否提供一个 demo？

**Comment by chn-lyzhi** [comment]
@tang3w 测试了多次，一旦项目的 Target 中 General 下 Linked Frameworks and Libraries 中引入 WebKit，或者 .swift 文件中 import WebKit 并初始化 WKWebView 都会出现上述问题
demo:[https://github.com/chn-lyzhi/testLeancloud.git](https://github.com/chn-lyzhi/testLeancloud.git)

**Comment by tang3w** [comment]
非常感谢你提供的 demo，已在 #41 中修复。请确认这个改动是否修复了你的问题。

**Comment by chn-lyzhi** [comment]
@tang3w OK，无问题

**Comment by tang3w** [comment]
已在 10.0.1 中修复。
