### ISSUE TITLE
集成 LeanCloud，但是在打包时出错，应该是SDK的问题

### ISSUE THREAD

**Issue by jwfing** [leancloud/swift-sdk#44]
![unnamed](https://cloud.githubusercontent.com/assets/985038/26185327/d5038ad4-3bbc-11e7-9cf6-393c5cd6978f.jpg)

**Comment by tang3w** [comment]
从用户提供的代码来看，不是最新版本的 SDK，新版 (v10.0.1) SDK 不存在这个问题。
