### ISSUE TITLE
cocopods集成报错

### ISSUE THREAD

**Issue by huapeng222** [leancloud/swift-sdk#48]
pod 'LeanCloud'

[!] There are only pre-release versions available satisfying the following requirements:

	'LeanCloud', '>= 0'

You should explicitly specify the version in order to install a pre-release version

**Comment by maxcong** [comment]
open the Podfile, then edit the platform :  
change : platform :ios, '10.0' => platform :ios, '8.0'

**Comment by tang3w** [comment]
请使用 pod 'LeanCloud', '~> 10.1.0'，然后使用 pod update 来更新。

**Comment by maxcong** [comment]
leanCloud是不是要放弃IOS 8(含8)以前的系统支持？

**Comment by maxcong** [comment]
另外Swift 4.0发布在即，希望语言版本能迅速跟进

**Comment by tang3w** [comment]
目前是支持 iOS 8.0 的，`pod 'LeanCloud', '~> 10.1.0'` 中的 `10.1.0` 是 SDK 的版本号。
我们会尽快支持 Swift 4。

**Comment by sonald** [comment]
什么时候支持swift4，或者有没有workaround？

**Comment by tang3w** [comment]
国庆节回来第一周计划支持一下。

**Comment by zapcannon87** [comment]
Supported Swift 4.0 in 11.0.0
