### ISSUE TITLE
与WKWebView冲突

### ISSUE THREAD

**Issue by zhenghongchuan** [leancloud/swift-sdk#49]
只要任何一个VC内集成了WKWebView，就会崩溃。具体崩溃点如图
![5e24bb86-5651-45b9-9946-ed213f5c9ada](https://user-images.githubusercontent.com/7361833/27446701-21bffca8-57b1-11e7-88a4-34331caf2512.png)

**Comment by tang3w** [comment]
Solved in v10.0.2.
