### ISSUE TITLE
Query 变成 LCQuery

### ISSUE THREAD

**Issue by jwfing** [leancloud/swift-sdk#6]
我们快点把接口改掉吧，这样才能发布。

**Comment by tang3w** [comment]
我后面又想了一下，加上 LC 可能有点不合适。因为这违背了 Swift 语言的 API 设计指南，发布出去会让人觉得奇怪。我准备把数据类型的 LC 前缀去掉，这样就跟 Python 和 JavaScript 保持一致了。

**Comment by tang3w** [comment]
已在 https://github.com/leancloud/swift-sdk/commit/4f2d9c8dbe89aae8afbc06b6a2cd706f2564dc83 中实现。
