### ISSUE TITLE
SDK 支持多应用的方案中，关于序列化部分的建议

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/swift-sdk#64]
在 https://github.com/leancloud/swift-sdk/pull/63 的基础上，主要改动有以下几点。

1. `LCApplication` 支持序列化
```
public final class LCApplication: NSCoding {
    
    /// 这三个是必须要序列化的，可以让 Region 带上 String 类型来支持序列化
    public let ID: String
    public let key: String
    public let region: Region
    
    /// logLevel 变为 static 可能更好一点，也能更省事不用序列化了
    public static var logLevel: LogLevel = .off
    
    // current, currentKey 还有 perform() 可以删掉了
    /*
     public static var current: LCApplication?
     private static let currentKey = "CurrentLeanCloudApplication"
     public func perform<T>(body: () throws -> T) rethrows -> T
     */

    // 其它的应该不用改动了
}
```

2. 然后就是在 `LCObject` 和 `LCQuery` 在序列化方法里加上 application 属性的序列化代码

3. 最后就是根据以上两点，对代码的其它部分进行相应的调整

**Comment by tang3w** [comment]
这个方案会导致内存中可能同时存在多个具有相同 app id 的 application 实例。为了避免本来表示同一个 application 的多个实例关联不同的信息，不得不把 id, key, region 之外的实例属性变成 static 属性。把 logLevel 改成 static 属性也是为了规避这个问题。但是，未来可能还会出现其他 application-specific 的信息。例如，current user 也应该关联到 application 实例上。

我建议对同一个 app id，只在内存中维护一个 application 实例。Application 不需要支持 NSCoding。Object 和 application 之间可以用 app id 进行关联，归档可能也更好处理一些。

**Comment by tang3w** [comment]
LCApplication 的构造函数干脆也不要公开了。不过这样一来，SDK 初始化接口又要改了。

**Comment by tang3w** [comment]
例如，是否接口是否可以设计成：

```swift
class LCApplication {
    static func setDefault(id: String, key: String, region: LCApplication.Region) -> LCApplication
    static func getDefault(id: String) -> LCApplication?
    static func add(id: String, key: String, region: LCApplication.Region) -> LCApplication
    static func get(id: String) -> LCApplication?
}
```

以上接口可以保证 app id 和 application 的一一映射，但长得不是很好看。

**Comment by zapcannon87** [comment]
我感觉你说的这个方案好像更好一点。

但是我咨询了其它 SDK 的看法和意见后，大家觉得在 native 平台的 SDK 对多应用的支持好像没什么需求，JS 那边主要也是服务端的需求，所以打算先让 JS 试水吧，其它 SDK 根据需求再看。

https://github.com/leancloud/swift-sdk/pull/63  这个 PR 就先把多应用的部分删掉吧。
