### ISSUE TITLE
业务变动,新加了字段,加载老数据的时候会crash

### ISSUE THREAD

**Issue by huapeng222** [leancloud/swift-sdk#65]
我是使用下边的方法去获取message
let message:String = (messageList[indexPath.row].get("message")?.stringValue)!

假设我现在新业务多了另一个属性,message2
let message2:String = (messageList[indexPath.row].get("message2")?.stringValue)!

新的数据,没有问题,老的数据这行报错
尝试判断messageList[indexPath.row].get("message2")是否为空,无效,是否有其他办法来处理这个问题,
另外我看后台数据库所有的数据都有了该字段,但是请求回来的数据没有该字段

**Comment by tang3w** [comment]
请在 Xcode 中添加异常断点并复现一下问题，然后把异常堆栈的截图发到 issue 中。

如果你购买了工单服务，也可以给我们提个工单。

**Comment by tang3w** [comment]
因长期没有回复，先关闭 issue 了。有问题请再反馈。
