### ISSUE TITLE
Missing argument for parameter 'capacity' in call

### ISSUE THREAD

**Issue by dalekzhangdong** [leancloud/swift-sdk#67]
![df3b9742-a74d-4c4b-828c-71f4afe7ea4a](https://user-images.githubusercontent.com/24927522/44712580-ba052e80-aae3-11e8-8fea-fb819170ec56.png)

**Comment by dalekzhangdong** [comment]
ios swift 导入sdk 出现如上问题，编译不通过

**Comment by dalekzhangdong** [comment]
![image](https://user-images.githubusercontent.com/24927522/44712789-2aac4b00-aae4-11e8-8fc2-270f15bd48e4.png)

**Comment by tang3w** [comment]
请确保 Xcode 是比较新的版本，目前在 Xcode 9.4.1 中编译正常。
