### ISSUE TITLE
循环引用

### ISSUE THREAD

**Issue by cavanlee** [leancloud/swift-sdk#87]
HTTPClient 和 HTTPRouter 相互持有对方，不会造成循环引用吗？

**Comment by tang3w** [comment]
这里的确存在循环引用，但这是 by design 的。因为 HTTPClient 是作为单例使用的，SDK 不会持续产生新的 HTTPClient 或 HTTPRouter 实例，因此不会导致内存泄漏。不过应该写一下注释。
