### ISSUE TITLE
Swift 13.0.0 version can't search for cocoapods 

### ISSUE THREAD

**Issue by caihong0622** [leancloud/swift-sdk#96]
<img width="833" alt="2018-10-26 5 56 24" src="https://user-images.githubusercontent.com/42528447/47559590-7c3c4f00-d948-11e8-8d0f-8c5c74e9fc88.png">

**Comment by caihong0622** [comment]
I update my podsec also can't find

**Comment by tang3w** [comment]
13.0.0 is pushed to CocoaPods now.
